config/routes.rb
Rails.application.routes.draw do
  get 'kombats/index', as: 'kombats'
  post 'kombats/fight', as: 'kombat'
  get 'kombats/form', as: 'kombat_form'
  root 'kombats#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/kombat_logic.rb
# Handle logic around resolving disagreements (peacefully).

# Tech design:
# The user will provide a SEED number between 1-9
# Retrieve the bio for each character and parse the “description” field
# Choose the WORD in each description at the position corresponding to the provided SEED
# The winner of the battle is the character whose WORD has the most characters EXCEPT if either character's WORD is a MAGIC WORD “Gamma” or “Radioactive” they automatically Win
# Present the winning character to the user
# Handle any errors or edge cases and display the message in a user friendly manner

module KombatLogic
  extend ActiveSupport::Concern

  INSTANT_WINS = ['gamma', 'radioactive'].freeze
  SPLIT_REGEX = %r{\s+}.freeze
  DESCRIPTION_CLEANUP_REGEX = %r{[[:punct:]]}.freeze
  TIE = 0.freeze
  ERROR = -1.freeze
  IDENTICAL = -2.freeze
  SEED_NUMBER_MAX = 9.freeze

  def calculate_fight_outcome(params)
    return { outcome: IDENTICAL } if params[:hero_1] == params[:hero_2] # No parallel universe fights please

    begin
      marvel = MarvelService.new
      hero1 = marvel.hero_data_for params[:hero_1]
      hero2 = marvel.hero_data_for params[:hero_2]
    rescue MarvelService::APIError => e
      return { outcome: ERROR, reason: e.message }
    end

    h1_value = calculate_fight_value hero1, params[:hero_1_seed].to_i
    h2_value = calculate_fight_value hero2, params[:hero_2_seed].to_i

    outcome_code = calculate_winner h1_value, h2_value
    {
      outcome: outcome_code,
      hero_1: hero1,
      hero_2: hero2
    }
  end

  def calculate_winner(h1_value, h2_value)
    # Note that we are assuming here that radioactive doesn't beat gamma
    # because it's longer
    h1_instant_win = INSTANT_WINS.include? h1_value
    h2_instant_win = INSTANT_WINS.include? h2_value

    # Ugmo
    if h1_instant_win && h2_instant_win
      TIE
    elsif h1_instant_win
      1
    elsif h2_instant_win
      2
    elsif h1_value.length == h2_value.length
      TIE
    elsif h1_value.length > h2_value.length
      1
    else
      2
    end
  end

  def calculate_fight_value(hero, seed)
    result = hero[:description].split(SPLIT_REGEX)
      .map { |s| s.gsub(DESCRIPTION_CLEANUP_REGEX, '') }
      .map(&:downcase)[seed - 1] # Adjust seed to array notation

    result
  end
end

app/controllers/kombats_controller.rb
class KombatsController < ApplicationController
  include KombatLogic

  def index; end

  def fight
    # Outcome is in the KombatLogic concern.
    # Display logic is in kombats_helper.
    @result = calculate_fight_outcome params
    Rails.logger.debug @result
    respond_to { |format| format.js }
  end

  def form
    # We do this in its own async function because we call the marvel api a bunch
    # to get the full slate of results, and it's slow page load.
    # Some heroes (like, for ex, 3-D Man) don't have descriptions,
    # or may have descriptions under the seed #. Filter those out.
    # Poor 3-D Man :(
    @hero_selection = MarvelService.new.hero_selection
      .reject { |x| x[:description].blank? || x[:description].split(SPLIT_REGEX).count < SEED_NUMBER_MAX }
      .map { |x| [x[:name], x[:id]] }
    render partial: 'kombats/form'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kombats_helper.rb
module KombatsHelper
  def display(result)
    return same_thing if result[:outcome] == KombatLogic::IDENTICAL
    return display_tie(result) if result[:outcome] == KombatLogic::TIE
    return display_error(result) if result[:outcome] == KombatLogic::ERROR
    display_winner(result)
  end

  private

  def same_thing
    safe_join([
      content_tag(:p, 'Same hero!'),
      image_tag('spiderman-pointing-spiderman.jpg')
    ])
  end

  def display_winner(result)
    # Ternaries here are pretty brittle
    winner = result[:outcome] == 1 ? result[:hero_1] : result[:hero_2]
    loser = result[:outcome] == 1 ? result[:hero_2] : result[:hero_1]
    safe_join([
      content_tag(:p, "According to our supercomputer,"),
      content_tag(:h3, "#{winner[:name]}"),
      content_tag(:p, "would defeat"),
      content_tag(:h3, "#{loser[:name]}"),
    ])
  end

  def display_tie(result)
    safe_join([
      content_tag(:p, "#{result[:hero_1][:name]} and #{result[:hero_2][:name]} are equally powerful in this matchup.")
    ]) 
  end

  def display_error(result)
    safe_join([
      content_tag(:p, 'Sorry, we hit an error getting character information.'),
      content_tag(:p, "Error detail from service: #{result[:reason]}")
    ])
  end
end

app/views/kombats/_form.html.erb
<% cache render_async_cache_key(request.path), skip_digest: true do %>
  <%= form_with url: kombat_path, method: :post do %>
    <div class="hero-1-input">
      <h2>Select one hero and a seed number:</h2>

      <%= select_tag :hero_1,
                     options_for_select(@hero_selection) %>
      <%= select_tag :hero_1_seed,
                     options_for_select((1..KombatLogic::SEED_NUMBER_MAX)) %>
    </div>

    <div class="hero-2-input">
      <h2>Select a second hero and a seed number:</h2>

      <div class="hero-2-name">
        <%= select_tag :hero_2,
                       options_for_select(@hero_selection) %>
        <%= select_tag :hero_2_seed,
                       options_for_select((1..KombatLogic::SEED_NUMBER_MAX)) %>
      </div>
    </div>
    <br />

    <div class="submit-section">
      <%= submit_tag :submit %>    
    </div>
  <% end %>  
<% end %>

app/views/kombats/fight.js.erb
var outcome = "<%= j display(@result) %>"

document.getElementById("result").innerHTML = outcome;

app/views/kombats/index.html.erb
<h1>Fight It Out</h1>
<p>Select heroes and seed numbers to see what Marvel hero would come out on top.</p>

<div class="form">
  <%= render_async_cache kombat_form_path, error_message: 'sorry, failed trying to load character list!' do %>
    loading...
  <% end %>
</div>

<p id="result"></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarvelKombat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_for :render_async %>
    
    <%= yield %>
  </body>
</html>